#
# DO NOT MODIFY!!!!
# This file is automatically generated by Racc 1.6.2
# from Racc grammar file "".
#

require 'racc/parser.rb'

require File.dirname(__FILE__) + '/parser.rex.rb'

module SOQLParser
  class Parser < Racc::Parser

module_eval(<<'...end parser.racc/module_eval...', 'parser.racc', 292)

def self.parse(soql)
  new.scan_str(soql)
end
...end parser.racc/module_eval...
##### State transition tables begin ###

racc_action_table = [
     3,    57,    77,    77,   111,    61,    13,    37,    61,   187,
    62,    63,     3,   188,     4,   221,    36,   178,   221,    40,
    41,    64,    65,  -107,    81,    80,     6,     3,   115,   -51,
    48,    40,    41,    13,    37,    28,    29,    30,    31,    32,
   149,  -132,  -131,    36,   121,    86,    61,    43,    44,    45,
    46,    47,   162,    61,     3,    57,   180,   181,    40,    41,
    13,    37,    28,    29,    30,    31,    32,   233,   234,    50,
    36,   239,   240,    54,    43,    44,    45,    46,    47,    59,
    61,    70,     8,    71,    72,    40,    41,    13,    37,    28,
    29,    30,    31,    32,    73,    74,    75,    36,    76,    78,
    79,    43,    44,    45,    46,    47,    83,    84,    85,    57,
    88,    89,    40,    41,    13,    37,    28,    29,    30,    31,
    32,    90,    96,    61,    68,   108,   112,   114,    43,    44,
    45,    46,    47,   132,    54,    61,    57,   135,   136,    40,
    41,    13,    37,    28,    29,    30,    31,    32,   137,   138,
   139,    36,   140,   141,   142,    43,    44,    45,    46,    47,
   144,   145,   149,     8,   160,   166,    40,    41,    13,    37,
    28,    29,    30,    31,    32,   171,    90,   182,    36,    47,
    61,   202,    43,    44,    45,    46,    47,   203,   149,   204,
    57,   -51,   160,    40,    41,    13,    37,    28,    29,    30,
    31,    32,   182,    47,   215,    36,   216,   171,   223,    43,
    44,    45,    46,    47,   224,   225,   226,    57,   227,   228,
    40,    41,    13,    37,    28,    29,    30,    31,    32,   229,
   230,   231,    36,   238,   nil,   nil,    43,    44,    45,    46,
    47,   nil,   nil,   nil,    57,   nil,   nil,    40,    41,    13,
    37,    28,    29,    30,    31,    32,   nil,   nil,   nil,    36,
   nil,   nil,   nil,    43,    44,    45,    46,    47,   nil,   nil,
   nil,    57,   nil,   nil,    40,    41,    13,    37,    28,    29,
    30,    31,    32,   nil,   nil,   nil,    36,   nil,   nil,   nil,
    43,    44,    45,    46,    47,   nil,   nil,   nil,    57,    99,
   nil,    40,    41,    13,    37,    28,    29,    30,    31,    32,
   nil,   nil,   nil,    36,   nil,   nil,   nil,    43,    44,    45,
    46,    47,   nil,   nil,   nil,    57,   nil,   nil,    40,    41,
    13,    37,    28,    29,    30,    31,    32,   nil,   nil,   nil,
    36,   nil,   nil,   nil,    43,    44,    45,    46,    47,   nil,
   nil,   nil,    57,   nil,   nil,    40,    41,    13,    37,    28,
    29,    30,    31,    32,   nil,   nil,   nil,    36,   nil,   nil,
   nil,    43,    44,    45,    46,    47,   nil,   nil,   nil,    57,
   nil,   nil,    40,    41,    13,    37,    28,    29,    30,    31,
    32,   nil,   nil,   nil,    36,   nil,   nil,   nil,    43,    44,
    45,    46,    47,   nil,   nil,   nil,    57,   nil,   nil,    40,
    41,    13,    37,    28,    29,    30,    31,    32,   nil,   nil,
   nil,    36,   nil,   nil,   nil,    43,    44,    45,    46,    47,
   nil,   nil,   nil,    57,   nil,   nil,    40,    41,    13,    37,
    28,    29,    30,    31,    32,   nil,   nil,   nil,    36,   nil,
   nil,   nil,    43,    44,    45,    46,    47,   nil,   nil,   nil,
   115,   nil,   nil,    40,    41,    13,    37,    28,    29,    30,
    31,    32,   105,   nil,   nil,    36,   121,   nil,   nil,    43,
    44,    45,    46,    47,   nil,   nil,   nil,   115,   nil,   nil,
    40,    41,    13,    37,    28,    29,    30,    31,    32,   nil,
   nil,   nil,    36,   nil,   nil,   nil,    43,    44,    45,    46,
    47,   nil,   nil,   nil,    57,   nil,   nil,    40,    41,    13,
    37,    28,    29,    30,    31,    32,   nil,   nil,   nil,    36,
   nil,   nil,   nil,    43,    44,    45,    46,    47,   nil,   nil,
   nil,   115,   nil,   nil,    40,    41,    13,    37,    28,    29,
    30,    31,    32,   nil,   nil,   nil,    36,   121,   nil,   nil,
    43,    44,    45,    46,    47,   nil,   nil,   nil,   115,   nil,
   nil,    40,    41,    13,    37,    28,    29,    30,    31,    32,
   nil,   nil,   nil,    36,   121,   nil,   nil,    43,    44,    45,
    46,    47,   -96,   -96,   -96,   -96,   nil,   nil,    40,    41,
   nil,   nil,    28,    29,    30,    31,    32,     8,   nil,   nil,
   nil,   nil,    13,    37,    43,    44,    45,    46,    47,   nil,
   nil,   nil,    36,   150,   151,   152,   153,   189,   154,   190,
   155,   nil,   nil,   156,   157,   158,   159,    40,    41,   nil,
   nil,    28,    29,    30,    31,    32,     8,   nil,   nil,   nil,
   nil,    13,    37,    43,    44,    45,    46,    47,   nil,   nil,
   nil,    36,   nil,   nil,   nil,   nil,   192,   nil,   193,   nil,
   nil,   nil,   nil,     8,   nil,   nil,    40,    41,    13,    37,
    28,    29,    30,    31,    32,   nil,   nil,   nil,    36,   nil,
   nil,   nil,    43,    44,    45,    46,    47,   nil,   nil,   nil,
     8,   nil,   nil,    40,    41,    13,    37,    28,    29,    30,
    31,    32,   nil,   nil,   nil,    36,   nil,   nil,   nil,    43,
    44,    45,    46,    47,   nil,   nil,   nil,     8,   nil,   nil,
    40,    41,    13,    37,    28,    29,    30,    31,    32,   nil,
   nil,   nil,    36,   nil,   nil,   nil,    43,    44,    45,    46,
    47,   nil,   nil,   nil,     8,   nil,   nil,    40,    41,    13,
    37,    28,    29,    30,    31,    32,   nil,   nil,   nil,    36,
   nil,   nil,   nil,    43,    44,    45,    46,    47,   nil,   nil,
   nil,   115,   nil,   nil,    40,    41,    13,    37,    28,    29,
    30,    31,    32,   nil,   nil,   nil,    36,   121,   nil,   nil,
    43,    44,    45,    46,    47,   nil,   nil,   nil,   nil,   nil,
   nil,    40,    41,   nil,   nil,    28,    29,    30,    31,    32,
     8,   nil,   nil,   nil,   nil,    13,    37,    43,    44,    45,
    46,    47,   nil,   nil,   nil,    36,   150,   151,   152,   153,
   189,   172,   190,   173,   nil,   nil,   174,   175,   176,   177,
    40,    41,   nil,   nil,    28,    29,    30,    31,    32,     8,
   nil,   nil,   nil,   nil,    13,    37,    43,    44,    45,    46,
    47,   nil,   nil,   nil,    36,   nil,   nil,   nil,   nil,   192,
   nil,   193,   nil,   nil,   nil,   nil,     8,   nil,   nil,    40,
    41,    13,    37,    28,    29,    30,    31,    32,   nil,   nil,
   nil,    36,   nil,   nil,   nil,    43,    44,    45,    46,    47,
   nil,   nil,   nil,     8,   nil,   nil,    40,    41,    13,    37,
    28,    29,    30,    31,    32,   nil,   nil,   nil,    36,   nil,
   nil,   nil,    43,    44,    45,    46,    47,   nil,   nil,   nil,
     8,   nil,   nil,    40,    41,    13,    37,    28,    29,    30,
    31,    32,   nil,   nil,   nil,    36,   nil,   nil,   nil,    43,
    44,    45,    46,    47,   nil,   nil,   nil,     8,   nil,   nil,
    40,    41,    13,    37,    28,    29,    30,    31,    32,   nil,
   nil,   nil,    36,   nil,   nil,   nil,    43,    44,    45,    46,
    47,   nil,   nil,   nil,    57,   nil,   nil,    40,    41,    13,
    37,    28,    29,    30,    31,    32,   nil,   nil,   nil,    36,
   nil,   nil,   nil,    43,    44,    45,    46,    47,   nil,   nil,
   nil,   nil,   nil,   nil,    40,    41,   nil,   nil,    28,    29,
    30,    31,    32,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
    43,    44,    45,    46,    47 ]

racc_action_check = [
     8,     8,    36,    68,    79,   203,     8,     8,   231,   153,
    16,    16,     0,   153,     1,   203,     8,   147,   231,    79,
    79,    17,    17,    13,    47,    47,     2,   115,   115,    13,
     4,     8,     8,   115,   115,     8,     8,     8,     8,     8,
   147,    36,    68,   115,   115,    53,    53,     8,     8,     8,
     8,     8,   135,   135,   182,   182,   150,   150,   115,   115,
   182,   182,   115,   115,   115,   115,   115,   219,   219,     5,
   182,   238,   238,     6,   115,   115,   115,   115,   115,    10,
    11,    25,     3,    28,    29,   182,   182,     3,     3,   182,
   182,   182,   182,   182,    30,    31,    32,     3,    33,    37,
    38,   182,   182,   182,   182,   182,    49,    50,    51,    18,
    54,    55,     3,     3,    18,    18,     3,     3,     3,     3,
     3,    58,    69,    70,    18,    77,    80,    82,     3,     3,
     3,     3,     3,    84,    85,    86,    57,    88,    98,    18,
    18,    57,    57,    18,    18,    18,    18,    18,   100,   101,
   102,    57,   103,   104,   105,    18,    18,    18,    18,    18,
   113,   114,   116,    59,   119,   143,    57,    57,    59,    59,
    57,    57,    57,    57,    57,   145,   148,   151,    59,   152,
   162,   165,    57,    57,    57,    57,    57,   166,   167,   168,
    62,   171,   179,    59,    59,    62,    62,    59,    59,    59,
    59,    59,   180,   181,   187,    62,   202,   204,   205,    59,
    59,    59,    59,    59,   206,   207,   208,    63,   209,   210,
    62,    62,    63,    63,    62,    62,    62,    62,    62,   213,
   214,   217,    63,   232,   nil,   nil,    62,    62,    62,    62,
    62,   nil,   nil,   nil,    64,   nil,   nil,    63,    63,    64,
    64,    63,    63,    63,    63,    63,   nil,   nil,   nil,    64,
   nil,   nil,   nil,    63,    63,    63,    63,    63,   nil,   nil,
   nil,    65,   nil,   nil,    64,    64,    65,    65,    64,    64,
    64,    64,    64,   nil,   nil,   nil,    65,   nil,   nil,   nil,
    64,    64,    64,    64,    64,   nil,   nil,   nil,    71,    71,
   nil,    65,    65,    71,    71,    65,    65,    65,    65,    65,
   nil,   nil,   nil,    71,   nil,   nil,   nil,    65,    65,    65,
    65,    65,   nil,   nil,   nil,    72,   nil,   nil,    71,    71,
    72,    72,    71,    71,    71,    71,    71,   nil,   nil,   nil,
    72,   nil,   nil,   nil,    71,    71,    71,    71,    71,   nil,
   nil,   nil,    73,   nil,   nil,    72,    72,    73,    73,    72,
    72,    72,    72,    72,   nil,   nil,   nil,    73,   nil,   nil,
   nil,    72,    72,    72,    72,    72,   nil,   nil,   nil,    74,
   nil,   nil,    73,    73,    74,    74,    73,    73,    73,    73,
    73,   nil,   nil,   nil,    74,   nil,   nil,   nil,    73,    73,
    73,    73,    73,   nil,   nil,   nil,    75,   nil,   nil,    74,
    74,    75,    75,    74,    74,    74,    74,    74,   nil,   nil,
   nil,    75,   nil,   nil,   nil,    74,    74,    74,    74,    74,
   nil,   nil,   nil,    76,   nil,   nil,    75,    75,    76,    76,
    75,    75,    75,    75,    75,   nil,   nil,   nil,    76,   nil,
   nil,   nil,    75,    75,    75,    75,    75,   nil,   nil,   nil,
    83,   nil,   nil,    76,    76,    83,    83,    76,    76,    76,
    76,    76,    76,   nil,   nil,    83,    83,   nil,   nil,    76,
    76,    76,    76,    76,   nil,   nil,   nil,   121,   nil,   nil,
    83,    83,   121,   121,    83,    83,    83,    83,    83,   nil,
   nil,   nil,   121,   nil,   nil,   nil,    83,    83,    83,    83,
    83,   nil,   nil,   nil,   142,   nil,   nil,   121,   121,   142,
   142,   121,   121,   121,   121,   121,   nil,   nil,   nil,   142,
   nil,   nil,   nil,   121,   121,   121,   121,   121,   nil,   nil,
   nil,   144,   nil,   nil,   142,   142,   144,   144,   142,   142,
   142,   142,   142,   nil,   nil,   nil,   144,   144,   nil,   nil,
   142,   142,   142,   142,   142,   nil,   nil,   nil,   149,   nil,
   nil,   144,   144,   149,   149,   144,   144,   144,   144,   144,
   nil,   nil,   nil,   149,   149,   nil,   nil,   144,   144,   144,
   144,   144,    15,    15,    15,    15,   nil,   nil,   149,   149,
   nil,   nil,   149,   149,   149,   149,   149,   154,   nil,   nil,
   nil,   nil,   154,   154,   149,   149,   149,   149,   149,   nil,
   nil,   nil,   154,   118,   118,   118,   118,   154,   118,   154,
   118,   nil,   nil,   118,   118,   118,   118,   154,   154,   nil,
   nil,   154,   154,   154,   154,   154,   155,   nil,   nil,   nil,
   nil,   155,   155,   154,   154,   154,   154,   154,   nil,   nil,
   nil,   155,   nil,   nil,   nil,   nil,   155,   nil,   155,   nil,
   nil,   nil,   nil,   156,   nil,   nil,   155,   155,   156,   156,
   155,   155,   155,   155,   155,   nil,   nil,   nil,   156,   nil,
   nil,   nil,   155,   155,   155,   155,   155,   nil,   nil,   nil,
   157,   nil,   nil,   156,   156,   157,   157,   156,   156,   156,
   156,   156,   nil,   nil,   nil,   157,   nil,   nil,   nil,   156,
   156,   156,   156,   156,   nil,   nil,   nil,   158,   nil,   nil,
   157,   157,   158,   158,   157,   157,   157,   157,   157,   nil,
   nil,   nil,   158,   nil,   nil,   nil,   157,   157,   157,   157,
   157,   nil,   nil,   nil,   159,   nil,   nil,   158,   158,   159,
   159,   158,   158,   158,   158,   158,   nil,   nil,   nil,   159,
   nil,   nil,   nil,   158,   158,   158,   158,   158,   nil,   nil,
   nil,   160,   nil,   nil,   159,   159,   160,   160,   159,   159,
   159,   159,   159,   nil,   nil,   nil,   160,   160,   nil,   nil,
   159,   159,   159,   159,   159,   nil,   nil,   nil,   nil,   nil,
   nil,   160,   160,   nil,   nil,   160,   160,   160,   160,   160,
   172,   nil,   nil,   nil,   nil,   172,   172,   160,   160,   160,
   160,   160,   nil,   nil,   nil,   172,   146,   146,   146,   146,
   172,   146,   172,   146,   nil,   nil,   146,   146,   146,   146,
   172,   172,   nil,   nil,   172,   172,   172,   172,   172,   173,
   nil,   nil,   nil,   nil,   173,   173,   172,   172,   172,   172,
   172,   nil,   nil,   nil,   173,   nil,   nil,   nil,   nil,   173,
   nil,   173,   nil,   nil,   nil,   nil,   174,   nil,   nil,   173,
   173,   174,   174,   173,   173,   173,   173,   173,   nil,   nil,
   nil,   174,   nil,   nil,   nil,   173,   173,   173,   173,   173,
   nil,   nil,   nil,   175,   nil,   nil,   174,   174,   175,   175,
   174,   174,   174,   174,   174,   nil,   nil,   nil,   175,   nil,
   nil,   nil,   174,   174,   174,   174,   174,   nil,   nil,   nil,
   176,   nil,   nil,   175,   175,   176,   176,   175,   175,   175,
   175,   175,   nil,   nil,   nil,   176,   nil,   nil,   nil,   175,
   175,   175,   175,   175,   nil,   nil,   nil,   177,   nil,   nil,
   176,   176,   177,   177,   176,   176,   176,   176,   176,   nil,
   nil,   nil,   177,   nil,   nil,   nil,   176,   176,   176,   176,
   176,   nil,   nil,   nil,   230,   nil,   nil,   177,   177,   230,
   230,   177,   177,   177,   177,   177,   nil,   nil,   nil,   230,
   nil,   nil,   nil,   177,   177,   177,   177,   177,   nil,   nil,
   nil,   nil,   nil,   nil,   230,   230,   nil,   nil,   230,   230,
   230,   230,   230,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   230,   230,   230,   230,   230 ]

racc_action_pointer = [
    10,    14,    20,    79,    30,    59,    65,   nil,    -2,   nil,
    74,    72,   nil,    20,   nil,   559,   -23,   -14,   106,   nil,
   nil,   nil,   nil,   nil,   nil,    72,   nil,   nil,    80,    81,
    91,    92,    93,    95,   nil,   nil,    -7,    81,    52,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   -29,   nil,    94,
    96,   103,   nil,    38,   101,   107,   nil,   133,   117,   160,
   nil,   nil,   187,   214,   241,   268,   nil,   nil,    -6,   104,
   115,   295,   322,   349,   376,   403,   430,   107,   nil,   -14,
    73,   nil,   114,   457,   125,   126,   127,   nil,   129,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   134,   nil,
   144,   145,   146,   148,   149,   149,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   145,   147,    25,   135,   nil,   604,   136,
   nil,   484,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,    45,   nil,   nil,   nil,   nil,
   nil,   nil,   511,   149,   538,   167,   817,    13,   172,   565,
    36,   174,   126,   -10,   604,   643,   670,   697,   724,   751,
   778,   nil,   172,   nil,   nil,   164,   173,   161,   184,   nil,
   nil,   182,   817,   856,   883,   910,   937,   964,   nil,   164,
   199,   150,    52,   nil,   nil,   nil,   nil,   181,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   188,    -3,   199,   204,   210,   211,   212,   214,
   215,   nil,   nil,   225,   225,   nil,   nil,   226,   nil,    24,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   991,     0,   188,   nil,   nil,   nil,   nil,   nil,    25,   nil,
   nil ]

racc_action_default = [
  -143,  -143,  -143,  -143,  -143,   -21,  -143,    -2,  -143,    -5,
    -7,    -9,   -10,  -135,   -80,   -81,   -84,   -87,  -143,   -89,
   -90,   -91,   -92,   -94,   -95,  -143,   -98,   -99,  -143,  -143,
  -143,  -143,  -143,  -143,  -122,  -123,  -127,  -143,  -143,  -129,
  -133,  -134,  -136,  -137,  -138,  -139,  -140,  -143,   241,   -23,
  -143,   -11,   -13,   -16,   -51,  -143,    -4,  -143,  -143,  -143,
    -8,  -135,  -143,  -143,  -143,  -143,   -88,   -96,  -127,  -143,
  -143,  -143,  -143,  -143,  -143,  -143,  -143,  -125,  -126,  -143,
  -143,  -142,   -25,  -143,  -143,  -143,  -143,   -15,  -143,    -3,
   -93,    -6,   -82,   -83,   -85,   -86,  -131,   -97,  -143,  -101,
  -143,  -143,  -143,  -143,  -143,  -143,  -109,  -110,  -124,  -128,
  -130,  -132,  -141,   -30,  -143,  -143,   -24,   -36,  -143,   -52,
   -54,  -143,   -57,   -58,   -59,   -61,   -62,   -63,   -64,   -77,
   -78,   -79,   -22,   -12,   -14,   -19,  -100,  -102,  -103,  -104,
  -105,  -106,  -143,   -32,  -143,  -143,  -143,  -143,   -79,  -143,
  -143,  -143,  -143,  -143,  -143,  -143,  -143,  -143,  -143,  -143,
  -143,   -56,  -143,   -18,  -108,   -34,  -143,   -31,   -26,   -28,
   -29,  -135,  -143,  -143,  -143,  -143,  -143,  -143,   -60,   -53,
  -143,  -143,  -143,   -20,   -38,   -39,   -44,  -143,   -46,   -47,
   -48,   -66,   -49,   -50,   -65,   -67,   -68,   -69,   -70,   -55,
   -17,    -1,  -143,  -143,  -143,   -66,   -65,   -67,   -68,   -69,
   -70,   -37,   -43,  -143,   -42,   -45,   -35,   -33,  -112,  -116,
  -114,  -115,   -27,   -72,   -71,   -73,   -74,   -75,   -76,   -40,
  -143,  -143,  -119,  -117,  -118,   -41,  -111,  -113,  -143,  -120,
  -121 ]

racc_goto_table = [
    11,    60,    52,    12,    53,    58,   116,   169,   106,     9,
   213,   184,   186,     1,    69,     5,   218,    67,   170,    92,
    93,    94,    95,    49,    82,   113,   143,   165,   201,     7,
    51,   168,   217,   179,   199,   161,    66,   104,   147,   232,
   211,   212,   237,    87,   236,   146,   109,   110,   nil,   nil,
   nil,   nil,   nil,   nil,    58,   nil,    11,   nil,   235,    12,
    97,    67,    67,    67,    67,    91,   222,   167,    98,   100,
   101,   102,   103,   107,   164,    69,   134,   170,   nil,   nil,
   nil,   133,   nil,    53,   191,   194,   195,   196,   197,   198,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   205,   206,   207,   208,   209,   210,   nil,   nil,
   nil,   nil,   148,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   163,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   107,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   183,   200,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   214,
   183,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   220,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   220,   nil,   nil,   nil,   nil,   nil,   214 ]

racc_goto_check = [
    15,    16,    18,    11,    19,    15,    21,    23,    54,    13,
    30,    29,    32,     1,    45,     3,    55,    42,    24,    41,
    41,    43,    43,     4,     5,     6,     7,     8,     9,    10,
    17,    22,    25,    34,    35,    36,    46,    53,    21,    57,
    29,    32,    58,    16,    55,    28,    62,    63,   nil,   nil,
   nil,   nil,   nil,   nil,    15,   nil,    15,   nil,    30,    11,
    16,    42,    42,    42,    42,    13,    23,    21,    15,    15,
    15,    15,    15,    15,    54,    45,    16,    24,   nil,   nil,
   nil,    18,   nil,    19,    28,    28,    28,    28,    28,    28,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,    28,    28,    28,    28,    28,    28,   nil,   nil,
   nil,   nil,    15,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,    16,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,    15,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,    11,    16,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,    15,
    11,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,    16,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,    16,   nil,   nil,   nil,   nil,   nil,    15 ]

racc_goto_pointer = [
   nil,    13,   nil,    13,    18,   -25,   -57,   -87,  -116,  -137,
    26,     0,   nil,     6,   nil,    -3,   -10,    24,    -4,    -2,
   nil,   -77,  -114,  -138,  -127,  -171,   nil,   nil,   -70,  -140,
  -172,   nil,  -140,   nil,  -116,  -126,   -86,   nil,   nil,   nil,
   nil,   -43,    -1,   -43,   nil,    -4,    18,   nil,   nil,   nil,
   nil,   nil,   nil,   -39,   -68,  -187,   nil,  -180,  -190,   nil,
   nil,   nil,   -33,   -32 ]

racc_goto_default = [
   nil,    56,     2,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   117,    55,   nil,    10,   131,    26,   nil,   nil,    27,
   185,   nil,   nil,   nil,    21,   nil,   130,   126,   118,   nil,
   nil,   127,    42,   128,   119,   120,   122,   123,   124,   125,
   129,    14,    15,    16,    17,    18,    19,    20,    22,    23,
    24,    25,    33,   nil,   nil,   nil,   219,   nil,   nil,    34,
    35,    38,   nil,    39 ]

racc_reduce_table = [
  0, 0, :racc_error,
  8, 56, :_reduce_1,
  2, 57, :_reduce_2,
  3, 66, :_reduce_3,
  1, 67, :_reduce_none,
  1, 65, :_reduce_5,
  3, 68, :_reduce_6,
  1, 68, :_reduce_none,
  2, 69, :_reduce_8,
  1, 69, :_reduce_none,
  1, 69, :_reduce_none,
  2, 58, :_reduce_11,
  3, 72, :_reduce_12,
  1, 72, :_reduce_none,
  3, 73, :_reduce_14,
  2, 73, :_reduce_15,
  1, 73, :_reduce_none,
  5, 73, :_reduce_17,
  4, 73, :_reduce_18,
  3, 73, :_reduce_19,
  1, 75, :_reduce_none,
  0, 59, :_reduce_none,
  3, 59, :_reduce_22,
  0, 60, :_reduce_none,
  2, 60, :_reduce_24,
  0, 61, :_reduce_none,
  3, 61, :_reduce_26,
  3, 77, :_reduce_27,
  1, 77, :_reduce_none,
  1, 78, :_reduce_none,
  0, 62, :_reduce_none,
  2, 62, :_reduce_31,
  0, 63, :_reduce_none,
  3, 63, :_reduce_33,
  0, 64, :_reduce_none,
  2, 64, :_reduce_35,
  1, 81, :_reduce_none,
  4, 82, :_reduce_37,
  3, 82, :_reduce_38,
  1, 84, :_reduce_none,
  3, 84, :_reduce_40,
  3, 85, :_reduce_41,
  1, 85, :_reduce_none,
  4, 86, :_reduce_43,
  3, 86, :_reduce_44,
  4, 88, :_reduce_45,
  3, 88, :_reduce_46,
  3, 88, :_reduce_47,
  3, 88, :_reduce_48,
  3, 88, :_reduce_49,
  3, 88, :_reduce_50,
  1, 74, :_reduce_51,
  1, 76, :_reduce_none,
  3, 76, :_reduce_53,
  1, 89, :_reduce_none,
  3, 89, :_reduce_55,
  2, 90, :_reduce_56,
  1, 90, :_reduce_none,
  1, 91, :_reduce_none,
  1, 92, :_reduce_none,
  3, 92, :_reduce_60,
  1, 93, :_reduce_none,
  1, 93, :_reduce_none,
  1, 93, :_reduce_none,
  1, 93, :_reduce_none,
  3, 94, :_reduce_65,
  3, 94, :_reduce_66,
  3, 94, :_reduce_67,
  3, 94, :_reduce_68,
  3, 94, :_reduce_69,
  3, 94, :_reduce_70,
  5, 94, :_reduce_71,
  5, 94, :_reduce_72,
  5, 94, :_reduce_73,
  5, 94, :_reduce_74,
  5, 94, :_reduce_75,
  5, 94, :_reduce_76,
  1, 83, :_reduce_none,
  1, 83, :_reduce_none,
  1, 95, :_reduce_none,
  1, 70, :_reduce_none,
  1, 70, :_reduce_none,
  3, 96, :_reduce_82,
  3, 96, :_reduce_83,
  1, 96, :_reduce_none,
  3, 98, :_reduce_85,
  3, 98, :_reduce_86,
  1, 98, :_reduce_none,
  2, 99, :_reduce_88,
  1, 99, :_reduce_none,
  1, 101, :_reduce_none,
  1, 101, :_reduce_none,
  1, 101, :_reduce_none,
  3, 101, :_reduce_93,
  1, 102, :_reduce_none,
  1, 104, :_reduce_none,
  1, 104, :_reduce_none,
  3, 79, :_reduce_97,
  1, 79, :_reduce_none,
  1, 106, :_reduce_none,
  4, 103, :_reduce_100,
  3, 103, :_reduce_101,
  4, 103, :_reduce_102,
  4, 103, :_reduce_103,
  4, 103, :_reduce_104,
  4, 103, :_reduce_105,
  4, 103, :_reduce_106,
  1, 107, :_reduce_none,
  3, 108, :_reduce_none,
  1, 108, :_reduce_none,
  1, 109, :_reduce_none,
  3, 80, :_reduce_111,
  1, 80, :_reduce_none,
  3, 110, :_reduce_113,
  1, 111, :_reduce_none,
  1, 111, :_reduce_115,
  0, 112, :_reduce_none,
  1, 112, :_reduce_117,
  1, 112, :_reduce_118,
  0, 113, :_reduce_none,
  2, 113, :_reduce_120,
  2, 113, :_reduce_121,
  1, 105, :_reduce_none,
  1, 105, :_reduce_none,
  3, 114, :_reduce_124,
  2, 114, :_reduce_125,
  2, 114, :_reduce_126,
  1, 114, :_reduce_127,
  3, 115, :_reduce_128,
  1, 116, :_reduce_none,
  1, 117, :_reduce_none,
  2, 118, :_reduce_131,
  1, 118, :_reduce_132,
  1, 100, :_reduce_133,
  1, 100, :_reduce_134,
  1, 71, :_reduce_135,
  1, 97, :_reduce_none,
  1, 97, :_reduce_137,
  1, 97, :_reduce_138,
  1, 97, :_reduce_139,
  1, 97, :_reduce_140,
  3, 87, :_reduce_141,
  2, 87, :_reduce_142 ]

racc_reduce_n = 143

racc_shift_n = 241

racc_token_table = {
  false => 0,
  :error => 1,
  :SELECT => 2,
  :left_paren => 3,
  :right_paren => 4,
  :comma => 5,
  :FROM => 6,
  :AS => 7,
  :identifier => 8,
  :period => 9,
  :USING => 10,
  :SCOPE => 11,
  :WHERE => 12,
  :GROUP => 13,
  :BY => 14,
  :HAVING => 15,
  :ORDER => 16,
  :LIMIT => 17,
  :unsigned_integer => 18,
  :NOT => 19,
  :IN => 20,
  :LIKE => 21,
  :IS => 22,
  :NULL => 23,
  :not_equals_operator => 24,
  :null => 25,
  :equals_operator => 26,
  :OR => 27,
  :AND => 28,
  :less_than_operator => 29,
  :greater_than_operator => 30,
  :less_than_or_equals_operator => 31,
  :greater_than_or_equals_operator => 32,
  :plus_sign => 33,
  :minus_sign => 34,
  :asterisk => 35,
  :solidus => 36,
  :COUNT => 37,
  :AVG => 38,
  :MAX => 39,
  :MIN => 40,
  :SUM => 41,
  :func_args_list => 42,
  :ASC => 43,
  :DESC => 44,
  :NULLS => 45,
  :FIRST => 46,
  :LAST => 47,
  :E => 48,
  :datetime => 49,
  :date => 50,
  :date_literal => 51,
  :date_literal_with_arg => 52,
  :quote => 53,
  :character_string_literal => 54 }

racc_nt_base = 55

racc_use_result_var = true

Racc_arg = [
  racc_action_table,
  racc_action_check,
  racc_action_default,
  racc_action_pointer,
  racc_goto_table,
  racc_goto_check,
  racc_goto_default,
  racc_goto_pointer,
  racc_nt_base,
  racc_reduce_table,
  racc_token_table,
  racc_shift_n,
  racc_reduce_n,
  racc_use_result_var ]

Racc_token_to_s_table = [
  "$end",
  "error",
  "SELECT",
  "left_paren",
  "right_paren",
  "comma",
  "FROM",
  "AS",
  "identifier",
  "period",
  "USING",
  "SCOPE",
  "WHERE",
  "GROUP",
  "BY",
  "HAVING",
  "ORDER",
  "LIMIT",
  "unsigned_integer",
  "NOT",
  "IN",
  "LIKE",
  "IS",
  "NULL",
  "not_equals_operator",
  "null",
  "equals_operator",
  "OR",
  "AND",
  "less_than_operator",
  "greater_than_operator",
  "less_than_or_equals_operator",
  "greater_than_or_equals_operator",
  "plus_sign",
  "minus_sign",
  "asterisk",
  "solidus",
  "COUNT",
  "AVG",
  "MAX",
  "MIN",
  "SUM",
  "func_args_list",
  "ASC",
  "DESC",
  "NULLS",
  "FIRST",
  "LAST",
  "E",
  "datetime",
  "date",
  "date_literal",
  "date_literal_with_arg",
  "quote",
  "character_string_literal",
  "$start",
  "query_specification",
  "select_clause",
  "from_clause",
  "using_scope_clause",
  "where_clause",
  "group_by_clause",
  "having_clause",
  "order_by_clause",
  "limit_clause",
  "select_list",
  "subquery",
  "query_expression",
  "select_sublist",
  "derived_column",
  "value_expression",
  "column_name",
  "table_references",
  "table_reference",
  "table_name",
  "table_subquery",
  "search_condition",
  "grouping_column_reference_list",
  "grouping_column_reference",
  "column_reference",
  "sort_specification_list",
  "row_subquery",
  "in_predicate",
  "row_value_constructor",
  "in_predicate_value",
  "in_value_list",
  "like_predicate",
  "string_literal",
  "null_predicate",
  "boolean_term",
  "boolean_factor",
  "boolean_test",
  "boolean_primary",
  "predicate",
  "comparison_predicate",
  "row_value_constructor_element",
  "numeric_value_expression",
  "general_literal",
  "term",
  "factor",
  "sign",
  "value_expression_primary",
  "unsigned_value_specification",
  "general_set_function",
  "unsigned_literal",
  "unsigned_numeric_literal",
  "qualifier",
  "func_name",
  "func_arg_list",
  "func_arg_expr",
  "sort_specification",
  "sort_key",
  "ordering_specification",
  "nulls_ordering_specification",
  "exact_numeric_literal",
  "approximate_numeric_literal",
  "mantissa",
  "exponent",
  "signed_integer" ]

Racc_debug_parser = false

##### State transition tables end #####

# reduce 0 omitted

module_eval(<<'.,.,', 'parser.racc', 5)
  def _reduce_1(val, _values, result)
     result = SOQLParser::Statement::Query.new(val[0], val[1], val[2], val[3], val[4], val[5], val[6], val[7])
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 8)
  def _reduce_2(val, _values, result)
     result = SOQLParser::Statement::Select.new(val[1])
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 13)
  def _reduce_3(val, _values, result)
     result = SOQLParser::Statement::Subquery.new(val[1])
    result
  end
.,.,

# reduce 4 omitted

module_eval(<<'.,.,', 'parser.racc', 19)
  def _reduce_5(val, _values, result)
     result = SOQLParser::Statement::SelectList.new(val[0])
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 22)
  def _reduce_6(val, _values, result)
     result = Array(val[0]) + Array(val[2])
    result
  end
.,.,

# reduce 7 omitted

module_eval(<<'.,.,', 'parser.racc', 27)
  def _reduce_8(val, _values, result)
     result = SOQLParser::Statement::As.new(val[0], val[1])
    result
  end
.,.,

# reduce 9 omitted

# reduce 10 omitted

module_eval(<<'.,.,', 'parser.racc', 32)
  def _reduce_11(val, _values, result)
     result = SOQLParser::Statement::FromClause.new(val[1])
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 35)
  def _reduce_12(val, _values, result)
     result = Array(val[0]) + Array(val[2])
    result
  end
.,.,

# reduce 13 omitted

module_eval(<<'.,.,', 'parser.racc', 39)
  def _reduce_14(val, _values, result)
     result = SOQLParser::Statement::As.new(val[0], val[2])
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 40)
  def _reduce_15(val, _values, result)
     result = SOQLParser::Statement::As.new(val[0], val[1])
    result
  end
.,.,

# reduce 16 omitted

module_eval(<<'.,.,', 'parser.racc', 42)
  def _reduce_17(val, _values, result)
     result = SOQLParser::Statement::As.new(SOQLParser::Statement::Table.new(val[0], val[2]), val[4])
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 43)
  def _reduce_18(val, _values, result)
     result = SOQLParser::Statement::As.new(SOQLParser::Statement::Table.new(val[0], val[2]), val[3])
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 44)
  def _reduce_19(val, _values, result)
     result = SOQLParser::Statement::Table.new(val[0], val[2])
    result
  end
.,.,

# reduce 20 omitted

# reduce 21 omitted

module_eval(<<'.,.,', 'parser.racc', 51)
  def _reduce_22(val, _values, result)
     result = SOQLParser::Statement::UsingScope.new(val[2])
    result
  end
.,.,

# reduce 23 omitted

module_eval(<<'.,.,', 'parser.racc', 55)
  def _reduce_24(val, _values, result)
     result = SOQLParser::Statement::WhereClause.new(val[1])
    result
  end
.,.,

# reduce 25 omitted

module_eval(<<'.,.,', 'parser.racc', 59)
  def _reduce_26(val, _values, result)
     result = SOQLParser::Statement::GroupByClause.new(val[2])
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 62)
  def _reduce_27(val, _values, result)
     result = Array(val[0]) + Array(val[2])
    result
  end
.,.,

# reduce 28 omitted

# reduce 29 omitted

# reduce 30 omitted

module_eval(<<'.,.,', 'parser.racc', 70)
  def _reduce_31(val, _values, result)
     result = SOQLParser::Statement::HavingClause.new(val[1])
    result
  end
.,.,

# reduce 32 omitted

module_eval(<<'.,.,', 'parser.racc', 74)
  def _reduce_33(val, _values, result)
     result = SOQLParser::Statement::OrderBy.new(val[2])
    result
  end
.,.,

# reduce 34 omitted

module_eval(<<'.,.,', 'parser.racc', 78)
  def _reduce_35(val, _values, result)
     result = SOQLParser::Statement::LimitClause.new(SOQLParser::Statement::Integer.new(val[1]))
    result
  end
.,.,

# reduce 36 omitted

module_eval(<<'.,.,', 'parser.racc', 85)
  def _reduce_37(val, _values, result)
     result = SOQLParser::Statement::Not.new(SOQLParser::Statement::In.new(val[0], val[3]))
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 86)
  def _reduce_38(val, _values, result)
     result = SOQLParser::Statement::In.new(val[0], val[2])
    result
  end
.,.,

# reduce 39 omitted

module_eval(<<'.,.,', 'parser.racc', 90)
  def _reduce_40(val, _values, result)
     result = SOQLParser::Statement::InValueList.new(val[1])
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 93)
  def _reduce_41(val, _values, result)
     result = Array(val[0]) + Array(val[2])
    result
  end
.,.,

# reduce 42 omitted

module_eval(<<'.,.,', 'parser.racc', 100)
  def _reduce_43(val, _values, result)
     result = SOQLParser::Statement::Not.new(SOQLParser::Statement::Like.new(val[0], val[3]))
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 101)
  def _reduce_44(val, _values, result)
     result = SOQLParser::Statement::Like.new(val[0], val[2])
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 104)
  def _reduce_45(val, _values, result)
     result = SOQLParser::Statement::Not.new(SOQLParser::Statement::Is.new(val[0], SOQLParser::Statement::Null.new))
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 105)
  def _reduce_46(val, _values, result)
     result = SOQLParser::Statement::Is.new(val[0], SOQLParser::Statement::Null.new)
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 106)
  def _reduce_47(val, _values, result)
     result = SOQLParser::Statement::Not.new(SOQLParser::Statement::Equals.new(val[0], SOQLParser::Statement::Null.new))
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 107)
  def _reduce_48(val, _values, result)
     result = SOQLParser::Statement::Not.new(SOQLParser::Statement::Equals.new(val[0], SOQLParser::Statement::Null.new))
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 108)
  def _reduce_49(val, _values, result)
     result = SOQLParser::Statement::Equals.new(val[0], SOQLParser::Statement::Null.new)
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 109)
  def _reduce_50(val, _values, result)
     result = SOQLParser::Statement::Equals.new(val[0], SOQLParser::Statement::Null.new)
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 113)
  def _reduce_51(val, _values, result)
     result = SOQLParser::Statement::Table.new(val[0])
    result
  end
.,.,

# reduce 52 omitted

module_eval(<<'.,.,', 'parser.racc', 118)
  def _reduce_53(val, _values, result)
     result = SOQLParser::Statement::Or.new(val[0], val[2])
    result
  end
.,.,

# reduce 54 omitted

module_eval(<<'.,.,', 'parser.racc', 122)
  def _reduce_55(val, _values, result)
     result = SOQLParser::Statement::And.new(val[0], val[2])
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 125)
  def _reduce_56(val, _values, result)
     result = SOQLParser::Statement::Not.new(val[1])
    result
  end
.,.,

# reduce 57 omitted

# reduce 58 omitted

# reduce 59 omitted

module_eval(<<'.,.,', 'parser.racc', 133)
  def _reduce_60(val, _values, result)
     result = val[1]
    result
  end
.,.,

# reduce 61 omitted

# reduce 62 omitted

# reduce 63 omitted

# reduce 64 omitted

module_eval(<<'.,.,', 'parser.racc', 142)
  def _reduce_65(val, _values, result)
     result = SOQLParser::Statement::Equals.new(val[0], val[2])
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 143)
  def _reduce_66(val, _values, result)
     result = SOQLParser::Statement::Not.new(SOQLParser::Statement::Equals.new(val[0], val[2]))
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 144)
  def _reduce_67(val, _values, result)
     result = SOQLParser::Statement::Less.new(val[0], val[2])
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 145)
  def _reduce_68(val, _values, result)
     result = SOQLParser::Statement::Greater.new(val[0], val[2])
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 146)
  def _reduce_69(val, _values, result)
     result = SOQLParser::Statement::LessOrEquals.new(val[0], val[2])
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 147)
  def _reduce_70(val, _values, result)
     result = SOQLParser::Statement::GreaterOrEquals.new(val[0], val[2])
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 150)
  def _reduce_71(val, _values, result)
     result = SOQLParser::Statement::Equals.new(val[1], val[3], true)
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 151)
  def _reduce_72(val, _values, result)
     result = SOQLParser::Statement::Not.new(SOQLParser::Statement::Equals.new(val[1], val[3], true))
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 152)
  def _reduce_73(val, _values, result)
     result = SOQLParser::Statement::Less.new(val[1], val[3], true)
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 153)
  def _reduce_74(val, _values, result)
     result = SOQLParser::Statement::Greater.new(val[1], val[3], true)
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 154)
  def _reduce_75(val, _values, result)
     result = SOQLParser::Statement::LessOrEquals.new(val[1], val[3], true)
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 155)
  def _reduce_76(val, _values, result)
     result = SOQLParser::Statement::GreaterOrEquals.new(val[1], val[3], true)
    result
  end
.,.,

# reduce 77 omitted

# reduce 78 omitted

# reduce 79 omitted

# reduce 80 omitted

# reduce 81 omitted

module_eval(<<'.,.,', 'parser.racc', 169)
  def _reduce_82(val, _values, result)
     result = SOQLParser::Statement::Add.new(val[0], val[2])
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 170)
  def _reduce_83(val, _values, result)
     result = SOQLParser::Statement::Subtract.new(val[0], val[2])
    result
  end
.,.,

# reduce 84 omitted

module_eval(<<'.,.,', 'parser.racc', 174)
  def _reduce_85(val, _values, result)
     result = SOQLParser::Statement::Multiply.new(val[0], val[2])
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 175)
  def _reduce_86(val, _values, result)
     result = SOQLParser::Statement::Divide.new(val[0], val[2])
    result
  end
.,.,

# reduce 87 omitted

module_eval(<<'.,.,', 'parser.racc', 179)
  def _reduce_88(val, _values, result)
     result = val[0].new(val[1])
    result
  end
.,.,

# reduce 89 omitted

# reduce 90 omitted

# reduce 91 omitted

# reduce 92 omitted

module_eval(<<'.,.,', 'parser.racc', 186)
  def _reduce_93(val, _values, result)
     result = val[1]
    result
  end
.,.,

# reduce 94 omitted

# reduce 95 omitted

# reduce 96 omitted

module_eval(<<'.,.,', 'parser.racc', 196)
  def _reduce_97(val, _values, result)
     result = SOQLParser::Statement::QualifiedColumn.new(val[0], val[2])
    result
  end
.,.,

# reduce 98 omitted

# reduce 99 omitted

module_eval(<<'.,.,', 'parser.racc', 203)
  def _reduce_100(val, _values, result)
     result = SOQLParser::Statement::Count.new(val[2])
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 204)
  def _reduce_101(val, _values, result)
     result = SOQLParser::Statement::Count.new(nil)
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 205)
  def _reduce_102(val, _values, result)
     result = SOQLParser::Statement::Average.new(val[2])
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 206)
  def _reduce_103(val, _values, result)
     result = SOQLParser::Statement::Maximum.new(val[2])
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 207)
  def _reduce_104(val, _values, result)
     result = SOQLParser::Statement::Minimum.new(val[2])
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 208)
  def _reduce_105(val, _values, result)
     result = SOQLParser::Statement::Sum.new(val[2])
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 209)
  def _reduce_106(val, _values, result)
     result = SOQLParser::Statement::Function.new(val[0], val[2])
    result
  end
.,.,

# reduce 107 omitted

# reduce 108 omitted

# reduce 109 omitted

# reduce 110 omitted

module_eval(<<'.,.,', 'parser.racc', 223)
  def _reduce_111(val, _values, result)
     result = Array(val[0]) + Array(val[2])
    result
  end
.,.,

# reduce 112 omitted

module_eval(<<'.,.,', 'parser.racc', 227)
  def _reduce_113(val, _values, result)
     result = SOQLParser::Statement::OrderColumn.new(val[0], val[1], val[2])
    result
  end
.,.,

# reduce 114 omitted

module_eval(<<'.,.,', 'parser.racc', 231)
  def _reduce_115(val, _values, result)
     result = SOQLParser::Statement::Integer.new(val[0])
    result
  end
.,.,

# reduce 116 omitted

module_eval(<<'.,.,', 'parser.racc', 235)
  def _reduce_117(val, _values, result)
     result = SOQLParser::Statement::Ascending.new
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 236)
  def _reduce_118(val, _values, result)
     result = SOQLParser::Statement::Descending.new
    result
  end
.,.,

# reduce 119 omitted

module_eval(<<'.,.,', 'parser.racc', 240)
  def _reduce_120(val, _values, result)
     result = SOQLParser::Statement::NullsFirst.new
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 241)
  def _reduce_121(val, _values, result)
     result = SOQLParser::Statement::NullsLast.new
    result
  end
.,.,

# reduce 122 omitted

# reduce 123 omitted

module_eval(<<'.,.,', 'parser.racc', 249)
  def _reduce_124(val, _values, result)
     result = SOQLParser::Statement::Float.new("#{val[0]}.#{val[2]}".to_f)
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 250)
  def _reduce_125(val, _values, result)
     result = SOQLParser::Statement::Float.new(val[0])
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 251)
  def _reduce_126(val, _values, result)
     result = SOQLParser::Statement::Float.new("0.#{val[1]}".to_f)
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 252)
  def _reduce_127(val, _values, result)
     result = SOQLParser::Statement::Integer.new(val[0])
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 255)
  def _reduce_128(val, _values, result)
     result = SOQLParser::Statement::ApproximateFloat.new(val[0], val[2])
    result
  end
.,.,

# reduce 129 omitted

# reduce 130 omitted

module_eval(<<'.,.,', 'parser.racc', 264)
  def _reduce_131(val, _values, result)
     result = val[0].new(SOQLParser::Statement::Integer.new(val[1]))
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 265)
  def _reduce_132(val, _values, result)
     result = SOQLParser::Statement::Integer.new(val[0])
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 268)
  def _reduce_133(val, _values, result)
     result = SOQLParser::Statement::UnaryPlus
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 269)
  def _reduce_134(val, _values, result)
     result = SOQLParser::Statement::UnaryMinus
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 273)
  def _reduce_135(val, _values, result)
     result = SOQLParser::Statement::Column.new(val[0])
    result
  end
.,.,

# reduce 136 omitted

module_eval(<<'.,.,', 'parser.racc', 278)
  def _reduce_137(val, _values, result)
     result = SOQLParser::Statement::DateTime.new(val[0])
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 279)
  def _reduce_138(val, _values, result)
     result = SOQLParser::Statement::Date.new(val[0])
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 280)
  def _reduce_139(val, _values, result)
     result = SOQLParser::Statement::DateLiteral.new(val[0])
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 281)
  def _reduce_140(val, _values, result)
     result = SOQLParser::Statement::DateLiteral.new(*val[0].split(':'))
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 284)
  def _reduce_141(val, _values, result)
     result = SOQLParser::Statement::String.new(val[1])
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 285)
  def _reduce_142(val, _values, result)
     result = SOQLParser::Statement::String.new('')
    result
  end
.,.,

def _reduce_none(val, _values, result)
  val[0]
end

  end   # class Parser
end   # module SOQLParser
