#
# DO NOT MODIFY!!!!
# This file is automatically generated by Racc 1.7.3
# from Racc grammar file "parser.racc".
#

require 'racc/parser.rb'

require File.dirname(__FILE__) + '/parser.rex.rb'

module SOQLParser
  class Parser < Racc::Parser

module_eval(<<'...end parser.racc/module_eval...', 'parser.racc', 288)

def self.parse(soql)
  new.scan_str(soql)
end
...end parser.racc/module_eval...
##### State transition tables begin ###

racc_action_table = [
     3,    57,    77,    77,   178,   111,    13,    37,    61,  -103,
   187,    61,    62,    63,   188,   -47,    36,     3,   217,    40,
    41,   217,    64,    65,   149,     4,     3,   115,    81,    80,
    40,    41,    13,    37,    28,    29,    30,    31,    32,     6,
  -128,  -127,    36,   121,    86,    61,    43,    44,    45,    46,
    47,    48,     3,    57,   162,    61,    40,    41,    13,    37,
    28,    29,    30,    31,    32,   180,   181,    50,    36,   229,
   230,    54,    43,    44,    45,    46,    47,   235,   236,     8,
    59,    61,    40,    41,    13,    37,    28,    29,    30,    31,
    32,    70,    71,    72,    36,    73,    74,    75,    43,    44,
    45,    46,    47,    76,    78,    57,    79,    83,    40,    41,
    13,    37,    28,    29,    30,    31,    32,    84,    85,    88,
    68,    89,    90,    96,    43,    44,    45,    46,    47,    61,
   108,    57,   112,   114,    40,    41,    13,    37,    28,    29,
    30,    31,    32,   132,    54,    61,    36,   135,   136,   137,
    43,    44,    45,    46,    47,   138,   139,     8,   140,   141,
    40,    41,    13,    37,    28,    29,    30,    31,    32,   142,
   144,   145,    36,   149,   160,   166,    43,    44,    45,    46,
    47,   171,    90,    57,   182,    47,    40,    41,    13,    37,
    28,    29,    30,    31,    32,    61,   198,   199,    36,   149,
   200,   -47,    43,    44,    45,    46,    47,   160,   182,    57,
    47,   211,    40,    41,    13,    37,    28,    29,    30,    31,
    32,   212,   171,   219,    36,   220,   221,   222,    43,    44,
    45,    46,    47,   223,   224,    57,   225,   226,    40,    41,
    13,    37,    28,    29,    30,    31,    32,   227,   234,   nil,
    36,   nil,   nil,   nil,    43,    44,    45,    46,    47,   nil,
   nil,    57,   nil,   nil,    40,    41,    13,    37,    28,    29,
    30,    31,    32,   nil,   nil,   nil,    36,   nil,   nil,   nil,
    43,    44,    45,    46,    47,   nil,   nil,    57,    99,   nil,
    40,    41,    13,    37,    28,    29,    30,    31,    32,   nil,
   nil,   nil,    36,   nil,   nil,   nil,    43,    44,    45,    46,
    47,   nil,   nil,    57,   nil,   nil,    40,    41,    13,    37,
    28,    29,    30,    31,    32,   nil,   nil,   nil,    36,   nil,
   nil,   nil,    43,    44,    45,    46,    47,   nil,   nil,    57,
   nil,   nil,    40,    41,    13,    37,    28,    29,    30,    31,
    32,   nil,   nil,   nil,    36,   nil,   nil,   nil,    43,    44,
    45,    46,    47,   nil,   nil,    57,   nil,   nil,    40,    41,
    13,    37,    28,    29,    30,    31,    32,   nil,   nil,   nil,
    36,   nil,   nil,   nil,    43,    44,    45,    46,    47,   nil,
   nil,    57,   nil,   nil,    40,    41,    13,    37,    28,    29,
    30,    31,    32,   nil,   nil,   nil,    36,   nil,   nil,   nil,
    43,    44,    45,    46,    47,   nil,   nil,    57,   nil,   nil,
    40,    41,    13,    37,    28,    29,    30,    31,    32,   nil,
   nil,   nil,    36,   nil,   nil,   nil,    43,    44,    45,    46,
    47,   nil,   nil,   115,   nil,   nil,    40,    41,    13,    37,
    28,    29,    30,    31,    32,   105,   nil,   nil,    36,   121,
   nil,   nil,    43,    44,    45,    46,    47,   nil,   nil,   115,
   nil,   nil,    40,    41,    13,    37,    28,    29,    30,    31,
    32,   nil,   nil,   nil,    36,   nil,   nil,   nil,    43,    44,
    45,    46,    47,   nil,   nil,    57,   nil,   nil,    40,    41,
    13,    37,    28,    29,    30,    31,    32,   nil,   nil,   nil,
    36,   nil,   nil,   nil,    43,    44,    45,    46,    47,   nil,
   nil,   115,   nil,   nil,    40,    41,    13,    37,    28,    29,
    30,    31,    32,   nil,   nil,   nil,    36,   121,   nil,   nil,
    43,    44,    45,    46,    47,   nil,   nil,   115,   nil,   nil,
    40,    41,    13,    37,    28,    29,    30,    31,    32,   nil,
   nil,   nil,    36,   121,   nil,   nil,    43,    44,    45,    46,
    47,   nil,   nil,     8,   nil,   nil,    40,    41,    13,    37,
    28,    29,    30,    31,    32,   nil,   nil,   nil,    36,   nil,
   nil,   nil,    43,    44,    45,    46,    47,   nil,   nil,     8,
   nil,   nil,    40,    41,    13,    37,    28,    29,    30,    31,
    32,   nil,   nil,   nil,    36,   nil,   nil,   nil,    43,    44,
    45,    46,    47,   nil,   nil,     8,   nil,   nil,    40,    41,
    13,    37,    28,    29,    30,    31,    32,   nil,   nil,   nil,
    36,   nil,   nil,   nil,    43,    44,    45,    46,    47,   nil,
   nil,     8,   nil,   nil,    40,    41,    13,    37,    28,    29,
    30,    31,    32,   nil,   nil,   nil,    36,   nil,   nil,   nil,
    43,    44,    45,    46,    47,   nil,   nil,     8,   nil,   nil,
    40,    41,    13,    37,    28,    29,    30,    31,    32,   nil,
   nil,   nil,    36,   nil,   nil,   nil,    43,    44,    45,    46,
    47,   nil,   nil,     8,   nil,   nil,    40,    41,    13,    37,
    28,    29,    30,    31,    32,   nil,   nil,   nil,    36,   nil,
   nil,   nil,    43,    44,    45,    46,    47,   nil,   nil,   115,
   nil,   nil,    40,    41,    13,    37,    28,    29,    30,    31,
    32,   nil,   nil,   nil,    36,   121,   nil,   nil,    43,    44,
    45,    46,    47,   nil,   nil,     8,   nil,   nil,    40,    41,
    13,    37,    28,    29,    30,    31,    32,   nil,   nil,   nil,
    36,   nil,   nil,   nil,    43,    44,    45,    46,    47,   nil,
   nil,     8,   nil,   nil,    40,    41,    13,    37,    28,    29,
    30,    31,    32,   nil,   nil,   nil,    36,   nil,   nil,   nil,
    43,    44,    45,    46,    47,   nil,   nil,     8,   nil,   nil,
    40,    41,    13,    37,    28,    29,    30,    31,    32,   nil,
   nil,   nil,    36,   nil,   nil,   nil,    43,    44,    45,    46,
    47,   nil,   nil,     8,   nil,   nil,    40,    41,    13,    37,
    28,    29,    30,    31,    32,   nil,   nil,   nil,    36,   nil,
   nil,   nil,    43,    44,    45,    46,    47,   nil,   nil,     8,
   nil,   nil,    40,    41,    13,    37,    28,    29,    30,    31,
    32,   nil,   nil,   nil,    36,   nil,   nil,   nil,    43,    44,
    45,    46,    47,   nil,   nil,     8,   nil,   nil,    40,    41,
    13,    37,    28,    29,    30,    31,    32,   nil,   nil,   nil,
    36,   nil,   nil,   nil,    43,    44,    45,    46,    47,   nil,
   nil,    57,   nil,   nil,    40,    41,    13,    37,    28,    29,
    30,    31,    32,   nil,   nil,   nil,    36,   nil,   nil,   nil,
    43,    44,    45,    46,    47,   -92,   -92,   -92,   -92,   nil,
    40,    41,   nil,   nil,    28,    29,    30,    31,    32,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,    43,    44,    45,    46,
    47,   150,   151,   152,   153,   nil,   nil,   nil,   154,   155,
   156,   157,   158,   159,   150,   151,   152,   153,   nil,   nil,
   nil,   172,   173,   174,   175,   176,   177 ]

racc_action_check = [
     8,     8,    36,    68,   147,    79,     8,     8,   199,    13,
   153,   227,    16,    16,   153,    13,     8,     0,   199,    79,
    79,   227,    17,    17,   147,     1,   115,   115,    47,    47,
     8,     8,   115,   115,     8,     8,     8,     8,     8,     2,
    36,    68,   115,   115,    53,    53,     8,     8,     8,     8,
     8,     4,   182,   182,   135,   135,   115,   115,   182,   182,
   115,   115,   115,   115,   115,   150,   150,     5,   182,   215,
   215,     6,   115,   115,   115,   115,   115,   234,   234,     3,
    10,    11,   182,   182,     3,     3,   182,   182,   182,   182,
   182,    25,    28,    29,     3,    30,    31,    32,   182,   182,
   182,   182,   182,    33,    37,    18,    38,    49,     3,     3,
    18,    18,     3,     3,     3,     3,     3,    50,    51,    54,
    18,    55,    58,    69,     3,     3,     3,     3,     3,    70,
    77,    57,    80,    82,    18,    18,    57,    57,    18,    18,
    18,    18,    18,    84,    85,    86,    57,    88,    98,   100,
    18,    18,    18,    18,    18,   101,   102,    59,   103,   104,
    57,    57,    59,    59,    57,    57,    57,    57,    57,   105,
   113,   114,    59,   116,   119,   143,    57,    57,    57,    57,
    57,   145,   148,    62,   151,   152,    59,    59,    62,    62,
    59,    59,    59,    59,    59,   162,   165,   166,    62,   167,
   168,   171,    59,    59,    59,    59,    59,   179,   180,    63,
   181,   187,    62,    62,    63,    63,    62,    62,    62,    62,
    62,   198,   200,   201,    63,   202,   203,   204,    62,    62,
    62,    62,    62,   205,   206,    64,   209,   210,    63,    63,
    64,    64,    63,    63,    63,    63,    63,   213,   228,   nil,
    64,   nil,   nil,   nil,    63,    63,    63,    63,    63,   nil,
   nil,    65,   nil,   nil,    64,    64,    65,    65,    64,    64,
    64,    64,    64,   nil,   nil,   nil,    65,   nil,   nil,   nil,
    64,    64,    64,    64,    64,   nil,   nil,    71,    71,   nil,
    65,    65,    71,    71,    65,    65,    65,    65,    65,   nil,
   nil,   nil,    71,   nil,   nil,   nil,    65,    65,    65,    65,
    65,   nil,   nil,    72,   nil,   nil,    71,    71,    72,    72,
    71,    71,    71,    71,    71,   nil,   nil,   nil,    72,   nil,
   nil,   nil,    71,    71,    71,    71,    71,   nil,   nil,    73,
   nil,   nil,    72,    72,    73,    73,    72,    72,    72,    72,
    72,   nil,   nil,   nil,    73,   nil,   nil,   nil,    72,    72,
    72,    72,    72,   nil,   nil,    74,   nil,   nil,    73,    73,
    74,    74,    73,    73,    73,    73,    73,   nil,   nil,   nil,
    74,   nil,   nil,   nil,    73,    73,    73,    73,    73,   nil,
   nil,    75,   nil,   nil,    74,    74,    75,    75,    74,    74,
    74,    74,    74,   nil,   nil,   nil,    75,   nil,   nil,   nil,
    74,    74,    74,    74,    74,   nil,   nil,    76,   nil,   nil,
    75,    75,    76,    76,    75,    75,    75,    75,    75,   nil,
   nil,   nil,    76,   nil,   nil,   nil,    75,    75,    75,    75,
    75,   nil,   nil,    83,   nil,   nil,    76,    76,    83,    83,
    76,    76,    76,    76,    76,    76,   nil,   nil,    83,    83,
   nil,   nil,    76,    76,    76,    76,    76,   nil,   nil,   121,
   nil,   nil,    83,    83,   121,   121,    83,    83,    83,    83,
    83,   nil,   nil,   nil,   121,   nil,   nil,   nil,    83,    83,
    83,    83,    83,   nil,   nil,   142,   nil,   nil,   121,   121,
   142,   142,   121,   121,   121,   121,   121,   nil,   nil,   nil,
   142,   nil,   nil,   nil,   121,   121,   121,   121,   121,   nil,
   nil,   144,   nil,   nil,   142,   142,   144,   144,   142,   142,
   142,   142,   142,   nil,   nil,   nil,   144,   144,   nil,   nil,
   142,   142,   142,   142,   142,   nil,   nil,   149,   nil,   nil,
   144,   144,   149,   149,   144,   144,   144,   144,   144,   nil,
   nil,   nil,   149,   149,   nil,   nil,   144,   144,   144,   144,
   144,   nil,   nil,   154,   nil,   nil,   149,   149,   154,   154,
   149,   149,   149,   149,   149,   nil,   nil,   nil,   154,   nil,
   nil,   nil,   149,   149,   149,   149,   149,   nil,   nil,   155,
   nil,   nil,   154,   154,   155,   155,   154,   154,   154,   154,
   154,   nil,   nil,   nil,   155,   nil,   nil,   nil,   154,   154,
   154,   154,   154,   nil,   nil,   156,   nil,   nil,   155,   155,
   156,   156,   155,   155,   155,   155,   155,   nil,   nil,   nil,
   156,   nil,   nil,   nil,   155,   155,   155,   155,   155,   nil,
   nil,   157,   nil,   nil,   156,   156,   157,   157,   156,   156,
   156,   156,   156,   nil,   nil,   nil,   157,   nil,   nil,   nil,
   156,   156,   156,   156,   156,   nil,   nil,   158,   nil,   nil,
   157,   157,   158,   158,   157,   157,   157,   157,   157,   nil,
   nil,   nil,   158,   nil,   nil,   nil,   157,   157,   157,   157,
   157,   nil,   nil,   159,   nil,   nil,   158,   158,   159,   159,
   158,   158,   158,   158,   158,   nil,   nil,   nil,   159,   nil,
   nil,   nil,   158,   158,   158,   158,   158,   nil,   nil,   160,
   nil,   nil,   159,   159,   160,   160,   159,   159,   159,   159,
   159,   nil,   nil,   nil,   160,   160,   nil,   nil,   159,   159,
   159,   159,   159,   nil,   nil,   172,   nil,   nil,   160,   160,
   172,   172,   160,   160,   160,   160,   160,   nil,   nil,   nil,
   172,   nil,   nil,   nil,   160,   160,   160,   160,   160,   nil,
   nil,   173,   nil,   nil,   172,   172,   173,   173,   172,   172,
   172,   172,   172,   nil,   nil,   nil,   173,   nil,   nil,   nil,
   172,   172,   172,   172,   172,   nil,   nil,   174,   nil,   nil,
   173,   173,   174,   174,   173,   173,   173,   173,   173,   nil,
   nil,   nil,   174,   nil,   nil,   nil,   173,   173,   173,   173,
   173,   nil,   nil,   175,   nil,   nil,   174,   174,   175,   175,
   174,   174,   174,   174,   174,   nil,   nil,   nil,   175,   nil,
   nil,   nil,   174,   174,   174,   174,   174,   nil,   nil,   176,
   nil,   nil,   175,   175,   176,   176,   175,   175,   175,   175,
   175,   nil,   nil,   nil,   176,   nil,   nil,   nil,   175,   175,
   175,   175,   175,   nil,   nil,   177,   nil,   nil,   176,   176,
   177,   177,   176,   176,   176,   176,   176,   nil,   nil,   nil,
   177,   nil,   nil,   nil,   176,   176,   176,   176,   176,   nil,
   nil,   226,   nil,   nil,   177,   177,   226,   226,   177,   177,
   177,   177,   177,   nil,   nil,   nil,   226,   nil,   nil,   nil,
   177,   177,   177,   177,   177,    15,    15,    15,    15,   nil,
   226,   226,   nil,   nil,   226,   226,   226,   226,   226,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   226,   226,   226,   226,
   226,   118,   118,   118,   118,   nil,   nil,   nil,   118,   118,
   118,   118,   118,   118,   146,   146,   146,   146,   nil,   nil,
   nil,   146,   146,   146,   146,   146,   146 ]

racc_action_pointer = [
    15,    25,    33,    76,    51,    57,    63,   nil,    -2,   nil,
    75,    73,   nil,     6,   nil,   903,   -20,   -12,   102,   nil,
   nil,   nil,   nil,   nil,   nil,    82,   nil,   nil,    89,    90,
    92,    93,    94,   100,   nil,   nil,    -7,    86,    59,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   -24,   nil,    95,
   106,   113,   nil,    37,   110,   117,   nil,   128,   118,   154,
   nil,   nil,   180,   206,   232,   258,   nil,   nil,    -6,   105,
   121,   284,   310,   336,   362,   388,   414,   112,   nil,   -13,
    80,   nil,   120,   440,   135,   136,   137,   nil,   139,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   144,   nil,
   145,   151,   152,   154,   155,   164,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   155,   157,    24,   149,   nil,   942,   149,
   nil,   466,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,    47,   nil,   nil,   nil,   nil,
   nil,   nil,   492,   159,   518,   173,   955,     0,   178,   544,
    45,   181,   133,    -9,   570,   596,   622,   648,   674,   700,
   726,   nil,   187,   nil,   nil,   179,   183,   175,   195,   nil,
   nil,   192,   752,   778,   804,   830,   856,   882,   nil,   182,
   205,   158,    50,   nil,   nil,   nil,   nil,   188,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   203,     0,
   214,   219,   221,   222,   223,   229,   230,   nil,   nil,   232,
   232,   nil,   nil,   242,   nil,    27,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   908,     3,   204,   nil,
   nil,   nil,   nil,   nil,    32,   nil,   nil ]

racc_action_default = [
  -139,  -139,  -139,  -139,  -139,   -21,  -139,    -2,  -139,    -5,
    -7,    -9,   -10,  -131,   -76,   -77,   -80,   -83,  -139,   -85,
   -86,   -87,   -88,   -90,   -91,  -139,   -94,   -95,  -139,  -139,
  -139,  -139,  -139,  -139,  -118,  -119,  -123,  -139,  -139,  -125,
  -129,  -130,  -132,  -133,  -134,  -135,  -136,  -139,   237,   -23,
  -139,   -11,   -13,   -16,   -47,  -139,    -4,  -139,  -139,  -139,
    -8,  -131,  -139,  -139,  -139,  -139,   -84,   -92,  -123,  -139,
  -139,  -139,  -139,  -139,  -139,  -139,  -139,  -121,  -122,  -139,
  -139,  -138,   -25,  -139,  -139,  -139,  -139,   -15,  -139,    -3,
   -89,    -6,   -78,   -79,   -81,   -82,  -127,   -93,  -139,   -97,
  -139,  -139,  -139,  -139,  -139,  -139,  -105,  -106,  -120,  -124,
  -126,  -128,  -137,   -30,  -139,  -139,   -24,   -36,  -139,   -48,
   -50,  -139,   -53,   -54,   -55,   -57,   -58,   -59,   -60,   -73,
   -74,   -75,   -22,   -12,   -14,   -19,   -96,   -98,   -99,  -100,
  -101,  -102,  -139,   -32,  -139,  -139,  -139,  -139,   -75,  -139,
  -139,  -139,  -139,  -139,  -139,  -139,  -139,  -139,  -139,  -139,
  -139,   -52,  -139,   -18,  -104,   -34,  -139,   -31,   -26,   -28,
   -29,  -131,  -139,  -139,  -139,  -139,  -139,  -139,   -56,   -49,
  -139,  -139,  -139,   -20,   -38,   -39,   -44,  -139,   -46,   -61,
   -62,   -63,   -64,   -65,   -66,   -51,   -17,    -1,  -139,  -139,
  -139,   -61,   -62,   -63,   -64,   -65,   -66,   -37,   -43,  -139,
   -42,   -45,   -35,   -33,  -108,  -112,  -110,  -111,   -27,   -67,
   -68,   -69,   -70,   -71,   -72,   -40,  -139,  -139,  -115,  -113,
  -114,   -41,  -107,  -109,  -139,  -116,  -117 ]

racc_goto_table = [
    11,    60,    52,    12,    53,    58,   116,     9,   106,   169,
   170,   209,   184,   186,    69,     1,   214,    92,    93,    94,
    95,     5,    49,    82,   113,   143,   165,   197,     7,    51,
   168,   213,   179,    67,   195,   161,    66,   104,   147,   228,
   233,   207,   208,    87,   232,   146,   109,   110,   nil,   nil,
   nil,   nil,   nil,   nil,    58,   231,    11,   nil,   nil,    12,
    97,   nil,   nil,    91,   218,   170,   nil,   167,    98,   100,
   101,   102,   103,   107,   164,    69,   134,    67,    67,    67,
    67,   133,   nil,    53,   189,   190,   191,   192,   193,   194,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   201,   202,   203,   204,   205,   206,   nil,   nil,
   nil,   nil,   148,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   163,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   107,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   183,   196,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   210,
   183,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   216,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   216,   nil,   nil,
   nil,   nil,   nil,   210 ]

racc_goto_check = [
    15,    16,    18,    11,    19,    15,    21,    13,    54,    23,
    24,    30,    29,    32,    45,     1,    55,    41,    41,    43,
    43,     3,     4,     5,     6,     7,     8,     9,    10,    17,
    22,    25,    34,    42,    35,    36,    46,    53,    21,    57,
    58,    29,    32,    16,    55,    28,    62,    63,   nil,   nil,
   nil,   nil,   nil,   nil,    15,    30,    15,   nil,   nil,    11,
    16,   nil,   nil,    13,    23,    24,   nil,    21,    15,    15,
    15,    15,    15,    15,    54,    45,    16,    42,    42,    42,
    42,    18,   nil,    19,    28,    28,    28,    28,    28,    28,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,    28,    28,    28,    28,    28,    28,   nil,   nil,
   nil,   nil,    15,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,    16,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,    15,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,    11,    16,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,    15,
    11,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,    16,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,    16,   nil,   nil,
   nil,   nil,   nil,    15 ]

racc_goto_pointer = [
   nil,    15,   nil,    19,    17,   -26,   -58,   -88,  -117,  -138,
    25,     0,   nil,     4,   nil,    -3,   -10,    23,    -4,    -2,
   nil,   -77,  -115,  -136,  -135,  -168,   nil,   nil,   -70,  -139,
  -171,   nil,  -139,   nil,  -117,  -126,   -86,   nil,   nil,   nil,
   nil,   -45,    15,   -45,   nil,    -4,    18,   nil,   nil,   nil,
   nil,   nil,   nil,   -39,   -68,  -183,   nil,  -176,  -188,   nil,
   nil,   nil,   -33,   -32 ]

racc_goto_default = [
   nil,    56,     2,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   117,    55,   nil,    10,   131,    26,   nil,   nil,    27,
   185,   nil,   nil,   nil,    21,   nil,   130,   126,   118,   nil,
   nil,   127,    42,   128,   119,   120,   122,   123,   124,   125,
   129,    14,    15,    16,    17,    18,    19,    20,    22,    23,
    24,    25,    33,   nil,   nil,   nil,   215,   nil,   nil,    34,
    35,    38,   nil,    39 ]

racc_reduce_table = [
  0, 0, :racc_error,
  8, 55, :_reduce_1,
  2, 56, :_reduce_2,
  3, 65, :_reduce_3,
  1, 66, :_reduce_none,
  1, 64, :_reduce_5,
  3, 67, :_reduce_6,
  1, 67, :_reduce_none,
  2, 68, :_reduce_8,
  1, 68, :_reduce_none,
  1, 68, :_reduce_none,
  2, 57, :_reduce_11,
  3, 71, :_reduce_12,
  1, 71, :_reduce_none,
  3, 72, :_reduce_14,
  2, 72, :_reduce_15,
  1, 72, :_reduce_none,
  5, 72, :_reduce_17,
  4, 72, :_reduce_18,
  3, 72, :_reduce_19,
  1, 74, :_reduce_none,
  0, 58, :_reduce_none,
  3, 58, :_reduce_22,
  0, 59, :_reduce_none,
  2, 59, :_reduce_24,
  0, 60, :_reduce_none,
  3, 60, :_reduce_26,
  3, 76, :_reduce_27,
  1, 76, :_reduce_none,
  1, 77, :_reduce_none,
  0, 61, :_reduce_none,
  2, 61, :_reduce_31,
  0, 62, :_reduce_none,
  3, 62, :_reduce_33,
  0, 63, :_reduce_none,
  2, 63, :_reduce_35,
  1, 80, :_reduce_none,
  4, 81, :_reduce_37,
  3, 81, :_reduce_38,
  1, 83, :_reduce_none,
  3, 83, :_reduce_40,
  3, 84, :_reduce_41,
  1, 84, :_reduce_none,
  4, 85, :_reduce_43,
  3, 85, :_reduce_44,
  4, 87, :_reduce_45,
  3, 87, :_reduce_46,
  1, 73, :_reduce_47,
  1, 75, :_reduce_none,
  3, 75, :_reduce_49,
  1, 88, :_reduce_none,
  3, 88, :_reduce_51,
  2, 89, :_reduce_52,
  1, 89, :_reduce_none,
  1, 90, :_reduce_none,
  1, 91, :_reduce_none,
  3, 91, :_reduce_56,
  1, 92, :_reduce_none,
  1, 92, :_reduce_none,
  1, 92, :_reduce_none,
  1, 92, :_reduce_none,
  3, 93, :_reduce_61,
  3, 93, :_reduce_62,
  3, 93, :_reduce_63,
  3, 93, :_reduce_64,
  3, 93, :_reduce_65,
  3, 93, :_reduce_66,
  5, 93, :_reduce_67,
  5, 93, :_reduce_68,
  5, 93, :_reduce_69,
  5, 93, :_reduce_70,
  5, 93, :_reduce_71,
  5, 93, :_reduce_72,
  1, 82, :_reduce_none,
  1, 82, :_reduce_none,
  1, 94, :_reduce_none,
  1, 69, :_reduce_none,
  1, 69, :_reduce_none,
  3, 95, :_reduce_78,
  3, 95, :_reduce_79,
  1, 95, :_reduce_none,
  3, 97, :_reduce_81,
  3, 97, :_reduce_82,
  1, 97, :_reduce_none,
  2, 98, :_reduce_84,
  1, 98, :_reduce_none,
  1, 100, :_reduce_none,
  1, 100, :_reduce_none,
  1, 100, :_reduce_none,
  3, 100, :_reduce_89,
  1, 101, :_reduce_none,
  1, 103, :_reduce_none,
  1, 103, :_reduce_none,
  3, 78, :_reduce_93,
  1, 78, :_reduce_none,
  1, 105, :_reduce_none,
  4, 102, :_reduce_96,
  3, 102, :_reduce_97,
  4, 102, :_reduce_98,
  4, 102, :_reduce_99,
  4, 102, :_reduce_100,
  4, 102, :_reduce_101,
  4, 102, :_reduce_102,
  1, 106, :_reduce_none,
  3, 107, :_reduce_none,
  1, 107, :_reduce_none,
  1, 108, :_reduce_none,
  3, 79, :_reduce_107,
  1, 79, :_reduce_none,
  3, 109, :_reduce_109,
  1, 110, :_reduce_none,
  1, 110, :_reduce_111,
  0, 111, :_reduce_none,
  1, 111, :_reduce_113,
  1, 111, :_reduce_114,
  0, 112, :_reduce_none,
  2, 112, :_reduce_116,
  2, 112, :_reduce_117,
  1, 104, :_reduce_none,
  1, 104, :_reduce_none,
  3, 113, :_reduce_120,
  2, 113, :_reduce_121,
  2, 113, :_reduce_122,
  1, 113, :_reduce_123,
  3, 114, :_reduce_124,
  1, 115, :_reduce_none,
  1, 116, :_reduce_none,
  2, 117, :_reduce_127,
  1, 117, :_reduce_128,
  1, 99, :_reduce_129,
  1, 99, :_reduce_130,
  1, 70, :_reduce_131,
  1, 96, :_reduce_none,
  1, 96, :_reduce_133,
  1, 96, :_reduce_134,
  1, 96, :_reduce_135,
  1, 96, :_reduce_136,
  3, 86, :_reduce_137,
  2, 86, :_reduce_138 ]

racc_reduce_n = 139

racc_shift_n = 237

racc_token_table = {
  false => 0,
  :error => 1,
  :SELECT => 2,
  :left_paren => 3,
  :right_paren => 4,
  :comma => 5,
  :FROM => 6,
  :AS => 7,
  :identifier => 8,
  :period => 9,
  :USING => 10,
  :SCOPE => 11,
  :WHERE => 12,
  :GROUP => 13,
  :BY => 14,
  :HAVING => 15,
  :ORDER => 16,
  :LIMIT => 17,
  :unsigned_integer => 18,
  :NOT => 19,
  :IN => 20,
  :LIKE => 21,
  :IS => 22,
  :NULL => 23,
  :OR => 24,
  :AND => 25,
  :equals_operator => 26,
  :not_equals_operator => 27,
  :less_than_operator => 28,
  :greater_than_operator => 29,
  :less_than_or_equals_operator => 30,
  :greater_than_or_equals_operator => 31,
  :plus_sign => 32,
  :minus_sign => 33,
  :asterisk => 34,
  :solidus => 35,
  :COUNT => 36,
  :AVG => 37,
  :MAX => 38,
  :MIN => 39,
  :SUM => 40,
  :func_args_list => 41,
  :ASC => 42,
  :DESC => 43,
  :NULLS => 44,
  :FIRST => 45,
  :LAST => 46,
  :E => 47,
  :datetime => 48,
  :date => 49,
  :date_literal => 50,
  :date_literal_with_arg => 51,
  :quote => 52,
  :character_string_literal => 53 }

racc_nt_base = 54

racc_use_result_var = true

Racc_arg = [
  racc_action_table,
  racc_action_check,
  racc_action_default,
  racc_action_pointer,
  racc_goto_table,
  racc_goto_check,
  racc_goto_default,
  racc_goto_pointer,
  racc_nt_base,
  racc_reduce_table,
  racc_token_table,
  racc_shift_n,
  racc_reduce_n,
  racc_use_result_var ]
Ractor.make_shareable(Racc_arg) if defined?(Ractor)

Racc_token_to_s_table = [
  "$end",
  "error",
  "SELECT",
  "left_paren",
  "right_paren",
  "comma",
  "FROM",
  "AS",
  "identifier",
  "period",
  "USING",
  "SCOPE",
  "WHERE",
  "GROUP",
  "BY",
  "HAVING",
  "ORDER",
  "LIMIT",
  "unsigned_integer",
  "NOT",
  "IN",
  "LIKE",
  "IS",
  "NULL",
  "OR",
  "AND",
  "equals_operator",
  "not_equals_operator",
  "less_than_operator",
  "greater_than_operator",
  "less_than_or_equals_operator",
  "greater_than_or_equals_operator",
  "plus_sign",
  "minus_sign",
  "asterisk",
  "solidus",
  "COUNT",
  "AVG",
  "MAX",
  "MIN",
  "SUM",
  "func_args_list",
  "ASC",
  "DESC",
  "NULLS",
  "FIRST",
  "LAST",
  "E",
  "datetime",
  "date",
  "date_literal",
  "date_literal_with_arg",
  "quote",
  "character_string_literal",
  "$start",
  "query_specification",
  "select_clause",
  "from_clause",
  "using_scope_clause",
  "where_clause",
  "group_by_clause",
  "having_clause",
  "order_by_clause",
  "limit_clause",
  "select_list",
  "subquery",
  "query_expression",
  "select_sublist",
  "derived_column",
  "value_expression",
  "column_name",
  "table_references",
  "table_reference",
  "table_name",
  "table_subquery",
  "search_condition",
  "grouping_column_reference_list",
  "grouping_column_reference",
  "column_reference",
  "sort_specification_list",
  "row_subquery",
  "in_predicate",
  "row_value_constructor",
  "in_predicate_value",
  "in_value_list",
  "like_predicate",
  "string_literal",
  "null_predicate",
  "boolean_term",
  "boolean_factor",
  "boolean_test",
  "boolean_primary",
  "predicate",
  "comparison_predicate",
  "row_value_constructor_element",
  "numeric_value_expression",
  "general_literal",
  "term",
  "factor",
  "sign",
  "value_expression_primary",
  "unsigned_value_specification",
  "general_set_function",
  "unsigned_literal",
  "unsigned_numeric_literal",
  "qualifier",
  "func_name",
  "func_arg_list",
  "func_arg_expr",
  "sort_specification",
  "sort_key",
  "ordering_specification",
  "nulls_ordering_specification",
  "exact_numeric_literal",
  "approximate_numeric_literal",
  "mantissa",
  "exponent",
  "signed_integer" ]
Ractor.make_shareable(Racc_token_to_s_table) if defined?(Ractor)

Racc_debug_parser = false

##### State transition tables end #####

# reduce 0 omitted

module_eval(<<'.,.,', 'parser.racc', 5)
  def _reduce_1(val, _values, result)
     result = SOQLParser::Statement::Query.new(val[0], val[1], val[2], val[3], val[4], val[5], val[6], val[7])
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 8)
  def _reduce_2(val, _values, result)
     result = SOQLParser::Statement::Select.new(val[1])
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 13)
  def _reduce_3(val, _values, result)
     result = SOQLParser::Statement::Subquery.new(val[1])
    result
  end
.,.,

# reduce 4 omitted

module_eval(<<'.,.,', 'parser.racc', 19)
  def _reduce_5(val, _values, result)
     result = SOQLParser::Statement::SelectList.new(val[0])
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 22)
  def _reduce_6(val, _values, result)
     result = Array(val[0]) + Array(val[2])
    result
  end
.,.,

# reduce 7 omitted

module_eval(<<'.,.,', 'parser.racc', 27)
  def _reduce_8(val, _values, result)
     result = SOQLParser::Statement::As.new(val[0], val[1])
    result
  end
.,.,

# reduce 9 omitted

# reduce 10 omitted

module_eval(<<'.,.,', 'parser.racc', 32)
  def _reduce_11(val, _values, result)
     result = SOQLParser::Statement::FromClause.new(val[1])
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 35)
  def _reduce_12(val, _values, result)
     result = Array(val[0]) + Array(val[2])
    result
  end
.,.,

# reduce 13 omitted

module_eval(<<'.,.,', 'parser.racc', 39)
  def _reduce_14(val, _values, result)
     result = SOQLParser::Statement::As.new(val[0], val[2])
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 40)
  def _reduce_15(val, _values, result)
     result = SOQLParser::Statement::As.new(val[0], val[1])
    result
  end
.,.,

# reduce 16 omitted

module_eval(<<'.,.,', 'parser.racc', 42)
  def _reduce_17(val, _values, result)
     result = SOQLParser::Statement::As.new(SOQLParser::Statement::Table.new(val[0], val[2]), val[4])
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 43)
  def _reduce_18(val, _values, result)
     result = SOQLParser::Statement::As.new(SOQLParser::Statement::Table.new(val[0], val[2]), val[3])
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 44)
  def _reduce_19(val, _values, result)
     result = SOQLParser::Statement::Table.new(val[0], val[2])
    result
  end
.,.,

# reduce 20 omitted

# reduce 21 omitted

module_eval(<<'.,.,', 'parser.racc', 51)
  def _reduce_22(val, _values, result)
     result = SOQLParser::Statement::UsingScope.new(val[2])
    result
  end
.,.,

# reduce 23 omitted

module_eval(<<'.,.,', 'parser.racc', 55)
  def _reduce_24(val, _values, result)
     result = SOQLParser::Statement::WhereClause.new(val[1])
    result
  end
.,.,

# reduce 25 omitted

module_eval(<<'.,.,', 'parser.racc', 59)
  def _reduce_26(val, _values, result)
     result = SOQLParser::Statement::GroupByClause.new(val[2])
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 62)
  def _reduce_27(val, _values, result)
     result = Array(val[0]) + Array(val[2])
    result
  end
.,.,

# reduce 28 omitted

# reduce 29 omitted

# reduce 30 omitted

module_eval(<<'.,.,', 'parser.racc', 70)
  def _reduce_31(val, _values, result)
     result = SOQLParser::Statement::HavingClause.new(val[1])
    result
  end
.,.,

# reduce 32 omitted

module_eval(<<'.,.,', 'parser.racc', 74)
  def _reduce_33(val, _values, result)
     result = SOQLParser::Statement::OrderBy.new(val[2])
    result
  end
.,.,

# reduce 34 omitted

module_eval(<<'.,.,', 'parser.racc', 78)
  def _reduce_35(val, _values, result)
     result = SOQLParser::Statement::LimitClause.new(SOQLParser::Statement::Integer.new(val[1]))
    result
  end
.,.,

# reduce 36 omitted

module_eval(<<'.,.,', 'parser.racc', 85)
  def _reduce_37(val, _values, result)
     result = SOQLParser::Statement::Not.new(SOQLParser::Statement::In.new(val[0], val[3]))
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 86)
  def _reduce_38(val, _values, result)
     result = SOQLParser::Statement::In.new(val[0], val[2])
    result
  end
.,.,

# reduce 39 omitted

module_eval(<<'.,.,', 'parser.racc', 90)
  def _reduce_40(val, _values, result)
     result = SOQLParser::Statement::InValueList.new(val[1])
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 93)
  def _reduce_41(val, _values, result)
     result = Array(val[0]) + Array(val[2])
    result
  end
.,.,

# reduce 42 omitted

module_eval(<<'.,.,', 'parser.racc', 100)
  def _reduce_43(val, _values, result)
     result = SOQLParser::Statement::Not.new(SOQLParser::Statement::Like.new(val[0], val[3]))
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 101)
  def _reduce_44(val, _values, result)
     result = SOQLParser::Statement::Like.new(val[0], val[2])
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 104)
  def _reduce_45(val, _values, result)
     result = SOQLParser::Statement::Not.new(SOQLParser::Statement::Is.new(val[0], SOQLParser::Statement::Null.new))
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 105)
  def _reduce_46(val, _values, result)
     result = SOQLParser::Statement::Is.new(val[0], SOQLParser::Statement::Null.new)
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 109)
  def _reduce_47(val, _values, result)
     result = SOQLParser::Statement::Table.new(val[0])
    result
  end
.,.,

# reduce 48 omitted

module_eval(<<'.,.,', 'parser.racc', 114)
  def _reduce_49(val, _values, result)
     result = SOQLParser::Statement::Or.new(val[0], val[2])
    result
  end
.,.,

# reduce 50 omitted

module_eval(<<'.,.,', 'parser.racc', 118)
  def _reduce_51(val, _values, result)
     result = SOQLParser::Statement::And.new(val[0], val[2])
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 121)
  def _reduce_52(val, _values, result)
     result = SOQLParser::Statement::Not.new(val[1])
    result
  end
.,.,

# reduce 53 omitted

# reduce 54 omitted

# reduce 55 omitted

module_eval(<<'.,.,', 'parser.racc', 129)
  def _reduce_56(val, _values, result)
     result = val[1]
    result
  end
.,.,

# reduce 57 omitted

# reduce 58 omitted

# reduce 59 omitted

# reduce 60 omitted

module_eval(<<'.,.,', 'parser.racc', 138)
  def _reduce_61(val, _values, result)
     result = SOQLParser::Statement::Equals.new(val[0], val[2])
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 139)
  def _reduce_62(val, _values, result)
     result = SOQLParser::Statement::Not.new(SOQLParser::Statement::Equals.new(val[0], val[2]))
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 140)
  def _reduce_63(val, _values, result)
     result = SOQLParser::Statement::Less.new(val[0], val[2])
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 141)
  def _reduce_64(val, _values, result)
     result = SOQLParser::Statement::Greater.new(val[0], val[2])
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 142)
  def _reduce_65(val, _values, result)
     result = SOQLParser::Statement::LessOrEquals.new(val[0], val[2])
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 143)
  def _reduce_66(val, _values, result)
     result = SOQLParser::Statement::GreaterOrEquals.new(val[0], val[2])
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 146)
  def _reduce_67(val, _values, result)
     result = SOQLParser::Statement::Equals.new(val[1], val[3], true)
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 147)
  def _reduce_68(val, _values, result)
     result = SOQLParser::Statement::Not.new(SOQLParser::Statement::Equals.new(val[1], val[3], true))
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 148)
  def _reduce_69(val, _values, result)
     result = SOQLParser::Statement::Less.new(val[1], val[3], true)
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 149)
  def _reduce_70(val, _values, result)
     result = SOQLParser::Statement::Greater.new(val[1], val[3], true)
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 150)
  def _reduce_71(val, _values, result)
     result = SOQLParser::Statement::LessOrEquals.new(val[1], val[3], true)
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 151)
  def _reduce_72(val, _values, result)
     result = SOQLParser::Statement::GreaterOrEquals.new(val[1], val[3], true)
    result
  end
.,.,

# reduce 73 omitted

# reduce 74 omitted

# reduce 75 omitted

# reduce 76 omitted

# reduce 77 omitted

module_eval(<<'.,.,', 'parser.racc', 165)
  def _reduce_78(val, _values, result)
     result = SOQLParser::Statement::Add.new(val[0], val[2])
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 166)
  def _reduce_79(val, _values, result)
     result = SOQLParser::Statement::Subtract.new(val[0], val[2])
    result
  end
.,.,

# reduce 80 omitted

module_eval(<<'.,.,', 'parser.racc', 170)
  def _reduce_81(val, _values, result)
     result = SOQLParser::Statement::Multiply.new(val[0], val[2])
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 171)
  def _reduce_82(val, _values, result)
     result = SOQLParser::Statement::Divide.new(val[0], val[2])
    result
  end
.,.,

# reduce 83 omitted

module_eval(<<'.,.,', 'parser.racc', 175)
  def _reduce_84(val, _values, result)
     result = val[0].new(val[1])
    result
  end
.,.,

# reduce 85 omitted

# reduce 86 omitted

# reduce 87 omitted

# reduce 88 omitted

module_eval(<<'.,.,', 'parser.racc', 182)
  def _reduce_89(val, _values, result)
     result = val[1]
    result
  end
.,.,

# reduce 90 omitted

# reduce 91 omitted

# reduce 92 omitted

module_eval(<<'.,.,', 'parser.racc', 192)
  def _reduce_93(val, _values, result)
     result = SOQLParser::Statement::QualifiedColumn.new(val[0], val[2])
    result
  end
.,.,

# reduce 94 omitted

# reduce 95 omitted

module_eval(<<'.,.,', 'parser.racc', 199)
  def _reduce_96(val, _values, result)
     result = SOQLParser::Statement::Count.new(val[2])
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 200)
  def _reduce_97(val, _values, result)
     result = SOQLParser::Statement::Count.new(nil)
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 201)
  def _reduce_98(val, _values, result)
     result = SOQLParser::Statement::Average.new(val[2])
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 202)
  def _reduce_99(val, _values, result)
     result = SOQLParser::Statement::Maximum.new(val[2])
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 203)
  def _reduce_100(val, _values, result)
     result = SOQLParser::Statement::Minimum.new(val[2])
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 204)
  def _reduce_101(val, _values, result)
     result = SOQLParser::Statement::Sum.new(val[2])
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 205)
  def _reduce_102(val, _values, result)
     result = SOQLParser::Statement::Function.new(val[0], val[2])
    result
  end
.,.,

# reduce 103 omitted

# reduce 104 omitted

# reduce 105 omitted

# reduce 106 omitted

module_eval(<<'.,.,', 'parser.racc', 219)
  def _reduce_107(val, _values, result)
     result = Array(val[0]) + Array(val[2])
    result
  end
.,.,

# reduce 108 omitted

module_eval(<<'.,.,', 'parser.racc', 223)
  def _reduce_109(val, _values, result)
     result = SOQLParser::Statement::OrderColumn.new(val[0], val[1], val[2])
    result
  end
.,.,

# reduce 110 omitted

module_eval(<<'.,.,', 'parser.racc', 227)
  def _reduce_111(val, _values, result)
     result = SOQLParser::Statement::Integer.new(val[0])
    result
  end
.,.,

# reduce 112 omitted

module_eval(<<'.,.,', 'parser.racc', 231)
  def _reduce_113(val, _values, result)
     result = SOQLParser::Statement::Ascending.new
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 232)
  def _reduce_114(val, _values, result)
     result = SOQLParser::Statement::Descending.new
    result
  end
.,.,

# reduce 115 omitted

module_eval(<<'.,.,', 'parser.racc', 236)
  def _reduce_116(val, _values, result)
     result = SOQLParser::Statement::NullsFirst.new
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 237)
  def _reduce_117(val, _values, result)
     result = SOQLParser::Statement::NullsLast.new
    result
  end
.,.,

# reduce 118 omitted

# reduce 119 omitted

module_eval(<<'.,.,', 'parser.racc', 245)
  def _reduce_120(val, _values, result)
     result = SOQLParser::Statement::Float.new("#{val[0]}.#{val[2]}".to_f)
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 246)
  def _reduce_121(val, _values, result)
     result = SOQLParser::Statement::Float.new(val[0])
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 247)
  def _reduce_122(val, _values, result)
     result = SOQLParser::Statement::Float.new("0.#{val[1]}".to_f)
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 248)
  def _reduce_123(val, _values, result)
     result = SOQLParser::Statement::Integer.new(val[0])
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 251)
  def _reduce_124(val, _values, result)
     result = SOQLParser::Statement::ApproximateFloat.new(val[0], val[2])
    result
  end
.,.,

# reduce 125 omitted

# reduce 126 omitted

module_eval(<<'.,.,', 'parser.racc', 260)
  def _reduce_127(val, _values, result)
     result = val[0].new(SOQLParser::Statement::Integer.new(val[1]))
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 261)
  def _reduce_128(val, _values, result)
     result = SOQLParser::Statement::Integer.new(val[0])
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 264)
  def _reduce_129(val, _values, result)
     result = SOQLParser::Statement::UnaryPlus
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 265)
  def _reduce_130(val, _values, result)
     result = SOQLParser::Statement::UnaryMinus
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 269)
  def _reduce_131(val, _values, result)
     result = SOQLParser::Statement::Column.new(val[0])
    result
  end
.,.,

# reduce 132 omitted

module_eval(<<'.,.,', 'parser.racc', 274)
  def _reduce_133(val, _values, result)
     result = SOQLParser::Statement::DateTime.new(val[0])
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 275)
  def _reduce_134(val, _values, result)
     result = SOQLParser::Statement::Date.new(val[0])
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 276)
  def _reduce_135(val, _values, result)
     result = SOQLParser::Statement::DateLiteral.new(val[0])
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 277)
  def _reduce_136(val, _values, result)
     result = SOQLParser::Statement::DateLiteral.new(*val[0].split(':'))
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 280)
  def _reduce_137(val, _values, result)
     result = SOQLParser::Statement::String.new(val[1])
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 281)
  def _reduce_138(val, _values, result)
     result = SOQLParser::Statement::String.new('')
    result
  end
.,.,

def _reduce_none(val, _values, result)
  val[0]
end

  end   # class Parser
end   # module SOQLParser
